# Generated by Django 5.2.3 on 2025-07-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrecord',
            name='report_text',
            field=models.TextField(default='No report available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='severity',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
