# Generated by Django 5.2.3 on 2025-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_diagnosisrecord_report_text_diagnosisrecord_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrecord',
            name='diet_recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='possible_conditions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='precautions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='recommended_medications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='recommended_tests',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='recovery_timeline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='specialist_consultation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='urgency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
