# Generated by Django 5.2.3 on 2026-04-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_diagnosisrecord_diet_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrecord',
            name='doctor_final_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
