# Generated by Django 5.2.3 on 2026-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_diagnosisrecord_doctor_final_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisrecord',
            name='recovery_timeline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisrecord',
            name='severity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisrecord',
            name='urgency',
            field=models.TextField(blank=True, null=True),
        ),
    ]
