# Generated by Django 5.2.3 on 2026-04-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_diagnosisrecord_recovery_timeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrecord',
            name='doctor_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='final_medications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='final_tests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
