# Generated by Django 5.2.3 on 2026-05-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_diagnosisrecord_analysis_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisrecord',
            name='doctor_final_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisrecord',
            name='result',
            field=models.TextField(),
        ),
    ]
