# Generated by Django 5.2.3 on 2026-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_diagnosisrecord_doctor_final_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrecord',
            name='diagnosis_source',
            field=models.CharField(default='gpt', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='doctor_training_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='medical_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='risk_alerts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
