from django.urls import path
from .views import (RegisterView, GoogleLoginView, UserProfileView, SpecializationListView, LoginView, 
    AdminStatsView, AdminDeletePatientView, AdminDoctorListView, AdminDoctorActionView, AdminPatientListView, 
    CreateAppointmentView, DoctorAppointmentsView, AppointmentActionView, PatientAppointmentsView, DeleteAppointmentView, 
    CreateRazorpayOrderView, VerifyPaymentAndBookView, DoctorBusySlotView, DeleteBusySlotView, AdminDoctorPayoutListView, 
    AdminPayDoctorView, AdminPayAllDoctorsView, DoctorIncomeGraphView, AdminIncomeGraphView, AnalyzeDoctorDocuments,
    PatientHealthScoreView)
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path("appointments/<int:pk>/", DeleteAppointmentView.as_view()),
    path("admin/income-graph/", AdminIncomeGraphView.as_view()),
    path("doctor/analyze/<int:doctor_id>/", AnalyzeDoctorDocuments.as_view()),
    path("admin/doctor-payouts/", AdminDoctorPayoutListView.as_view()),
    path("doctor/income-graph/", DoctorIncomeGraphView.as_view()),
    path("admin/pay-doctor/<int:doctor_id>/", AdminPayDoctorView.as_view()),
    path("admin/pay-all-doctors/", AdminPayAllDoctorsView.as_view()),
    path("doctor/busy-slots/<int:pk>/delete/", DeleteBusySlotView.as_view()),
    path("register/", RegisterView.as_view()),
    path("doctor-busy-slots/", DoctorBusySlotView.as_view()),
    path("create-order/", CreateRazorpayOrderView.as_view()),
    path("verify-payment/", VerifyPaymentAndBookView.as_view()),
    path("appointments/create/", CreateAppointmentView.as_view()),
    path("appointments/doctor/", DoctorAppointmentsView.as_view()),
    path("appointments/patient/", PatientAppointmentsView.as_view()),
    path("appointments/action/<int:pk>/", AppointmentActionView.as_view()),
    path("admin/stats/", AdminStatsView.as_view()),
    path("admin/patients/", AdminPatientListView.as_view()),
    path("admin/patients/<int:pk>/", AdminDeletePatientView.as_view()),
    path("admin/doctors/", AdminDoctorListView.as_view()),
    path("admin/doctors/<int:pk>/", AdminDoctorActionView.as_view()),
    path("specializations/", SpecializationListView.as_view()),
    path("login/", LoginView.as_view()),
    path("google-login/", GoogleLoginView.as_view()),
    path("profile/", UserProfileView.as_view(), name="user-profile"),
    path("health-score/", PatientHealthScoreView.as_view(), name="patient-health-score"),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]
